Repository umijs/create-umi, pull requests merged in 2019-10, with the labels that each got.

#85 fix: ui plugin react deps should peerDeps
  lib/generators/plugin/templates/package.json
Labels: bug

#86 fix: set and use environment variables across platforms with cross-env
  lib/generators/plugin/templates/package.json
Labels: pr(bug)

#87 fix: app template routes use configuration
  lib/generators/app/templates/.umirc.js
  lib/generators/app/templates/.umirc.ts
Labels: pr(enhancement)

#88 feat: support plugin ui mini development and better debug
  .gitignore
  lib/BasicGenerator.js
  lib/generators/plugin/templates/README.md
  lib/generators/plugin/templates/example/.umirc.js
  lib/generators/plugin/templates/example/.umirc.ts
  lib/generators/plugin/templates/example/package.json
  lib/generators/plugin/templates/example/pages/index.js
  lib/generators/plugin/templates/example/pages/index.tsx
  lib/generators/plugin/templates/example/tsconfig.json
  lib/generators/plugin/templates/package.json
  lib/generators/plugin/templates/src/index.js
  lib/generators/plugin/templates/src/index.ts
Labels: enhancement

#90 fix: umi-types version
  lib/generators/plugin/templates/package.json
Labels: dependencies

#89 chore: Update welcome image
  lib/BasicGenerator.js
  lib/generators/app/templates/src/assets/welcomeImgs/0.jpg
  lib/generators/app/templates/src/assets/welcomeImgs/1.jpg
  lib/generators/app/templates/src/pages/index.css
Labels: pr(enhancement)

#91 fix: plugin readme and start script
  .codecov.yml
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  README.md
  circle.yml
  jest.config.js
  lib/generators/plugin/templates/README.md
  lib/generators/plugin/templates/package.json
  package.json
  test/fixtures/mock_cnpmjs.js
  test/index.test.js
  test/jest.setup.js
Labels: pr(bug)
